GET http://localhost:8000/browse

###

GET http://localhost:8000/browse/tstream

###

GET http://localhost:8000/browse/wstream

###

DELETE http://localhost:8000/browse
Content-Type: application/json

{
  "url": "http://192.168.0.78:8001/tstream/A1%20FHF%20200701.m4"
}

